version: "3.7"

services: 
  db:
    restart: always
    image: mysql:5.7
    volumes:
      - .tmp/db:/var/lib/mysql
    # ports:
    #   - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app

  redis:
    restart: always
    image: redis:5.0.7
    # ports:
    #   - '6380:6379'
    volumes:
      - .tmp/redis:/var/lib/redis/data

  webpack:
    restart: always
    build: .
    command: bash -c "yarn install --check-files && ./bin/webpack-dev-server"
    volumes:
      - ./:/app
    # ports:
    #   - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  app: 
    restart: always
    build: .
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "bundle update && bundle exec rails db:create db:migrate && bundle exec rails assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
      - webpack
    links:
      - db
      - redis
      - webpack
    env_file: 
      - .env
      
