default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || "plant_marketplace" %>
  username: <%= ENV['DB_USER'] || "username" %>
  password: <%= ENV['DB_PASSWORD'] || "password" %>
  host:     <%= ENV['DB_HOST'] || "localhost" %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || "plant_marketplace_test" %>
  username: <%= ENV['DB_USER'] || "username" %>
  password: <%= ENV['DB_PASSWORD'] || "password" %>
  host:     <%= ENV['DB_HOST'] || "localhost" %>

production:
  <<: *default